feat: добавлены контроллеры для User и Item
GeorgyMalkhozov/java-shareit pull request #1
Opened 2022-12-28 09:55 UTC by GeorgyMalkhozov

2022-12-28 19:43 UTC, EvgenyKoptubenko commented
Странно, но без этой зависимости
<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<version>2.2.3</version>
		</dependency>
Проект не запускался на Mac

2022-12-28 19:47 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDTO getItem(@PathVariable Integer id) {
Странно, но когда запрашивается несуществующий пользователь, то приходит 404 и описание ошибки. Когда не существует Item, то приходит 200 []

2022-12-28 19:49 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.searchItems(text);
Странно, но когда запрашивается несуществующий пользователь, то приходит 404 и описание ошибки. Когда не существует Item, то приходит 200 []
[http://localhost:8080/items/search?text="descriptionItem](http://localhost:8080/items/search?text=%22descriptionItem)"
И вне зависимости есть такой пользователь или нет - все равно приходит 200

2022-12-28 19:51 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exceptions/SqlException.java
> +        super(HttpStatus.NOT_FOUND, message);;
лишняя точка с запятой

2022-12-28 19:53 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final ItemMapper itemMapper;
переменная не используется

2022-12-28 19:56 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapper.java
> +    ItemRequestDTO requestToRequestDto(ItemRequest itemRequest);
похоже эти две функции нигде не используются

2022-12-28 20:00 UTC, EvgenyKoptubenko requested changes
Замечаний практически нет. Работа сделана очень хорошо. Работает по ТЗ

2022-12-29 20:07 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.searchItems(text);
Исправил: сейчас если введен какой-либо текст для @RequestParam и подходящие items не обнаружены, выбрасывается 404. Если запрос содержит только пустой items/search?text=, то статус 200, т.к. иначе 62-я проверка в postman не срабатывает.

2022-12-29 20:07 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/exceptions/SqlException.java
> +        super(HttpStatus.NOT_FOUND, message);;
исправил

2022-12-29 20:07 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final ItemMapper itemMapper;
исправил

2022-12-29 20:08 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapper.java
> +    ItemRequestDTO requestToRequestDto(ItemRequest itemRequest);
исправил

2022-12-30 14:41 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично.

2023-01-02 12:40 UTC, merged