feat: добавлены репозитории, функционал букинга и комментариев
GeorgyMalkhozov/java-shareit pull request #2
Opened 2023-01-13 19:31 UTC by GeorgyMalkhozov

2023-01-14 18:51 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserResponseDTO addUser(@RequestBody @Valid UserDTO dto) {
Если отправить во второй раз запрос на создание пользователя, то в сообщении присутствует лишняя информация о constraint. Попробуй добавить обработку ошибки
{
	"message": "DataIntegrityViolationException",
	"debugMessage": "could not execute statement; SQL [n/a]; constraint [\"PUBLIC.UK_6DOTKOTT2KJSP8VW4D0M25FB7_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'email322@email.com' )\"; SQL statement:\ninsert into public.users (id, email, name) values (default, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}

2023-01-14 18:52 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserResponseDTO updateItem(@PathVariable Integer id, @RequestBody @Valid UserUpdateDTO updateDto) {
Если отправить такой запрос
curl --request PATCH \
  --url http://localhost:8080/users/1 \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"wrong_emailmail.com",
  "login":"login22",
	"birthday":"2012-04-23T18:25:43.511Z"
}'

То приходит 500
{
	"message": "TransactionSystemException",
	"debugMessage": "Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction"
}

2023-01-14 18:54 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemResponseDTO addItem(@RequestBody @Valid ItemDTO dto, @RequestHeader("X-Sharer-User-Id") Integer userId) {
Если есть желание, попробуй добавить проверку входных данных
{
	"message": "MethodArgumentTypeMismatchException",
	"debugMessage": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: \"фф\""
}

2023-01-14 18:56 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Всего несколько предложений по улучшению

2023-01-16 21:24 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserResponseDTO addUser(@RequestBody @Valid UserDTO dto) {
добавил обработку

2023-01-16 21:25 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserResponseDTO updateItem(@PathVariable Integer id, @RequestBody @Valid UserUpdateDTO updateDto) {
добавил обработку

2023-01-16 21:25 UTC, GeorgyMalkhozov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemResponseDTO addItem(@RequestBody @Valid ItemDTO dto, @RequestHeader("X-Sharer-User-Id") Integer userId) {
добавил

2023-01-17 19:22 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-19 16:38 UTC, merged