feat: добавлены запросы вещей и тесты
GeorgyMalkhozov/java-shareit pull request #3
Opened 2023-01-29 15:21 UTC by GeorgyMalkhozov

2023-02-01 19:53 UTC, EvgenyKoptubenko commented
В классе BookingService на 121 строке идет преобразование строки в Enum
Почему не сделать
BookingState.valueOf(state);
вместо new BookingStateConverter().convert(state) ?

2023-02-01 19:56 UTC, EvgenyKoptubenko commented
В классе Booking используется @Data
@EqualsAndHashCode, что может негативно повлиять на производительность и потребление памяти

2023-02-01 19:58 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Замечаний по этому спринту нет.
Нашел два предложения по коду. Если есть желание - поправь, если нет - присылай обратно

2023-02-01 21:35 UTC, GeorgyMalkhozov commented
1. переделал конвертер в static класс в самом BookingState. в BookingService делать через valueOf не стал, чтобы потом переиспользовать код обработки исключения преобразования этого enum, если потребуется где-то еще
2. поправил

2023-02-02 18:41 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-02 19:06 UTC, merged